import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { backgroundColor: '#F7FAFB', flex: 1 },
  header: { alignItems: 'center', flexDirection: 'row', height: 44, justifyContent: 'space-between' },
  backButton: { alignItems: 'center', height: 44, justifyContent: 'center', width: 44 },
  headerTitle: { color: '#10161F', fontSize: 16, fontWeight: '600' },
  headerSpacer: { width: 44 },
  permissionState: { alignItems: 'center', flex: 1, justifyContent: 'center', paddingHorizontal: 24 },
  permissionTitle: { color: '#10161F', fontSize: 18, fontWeight: '700', textAlign: 'center' },
  permissionMessage: { color: '#8A9194', fontSize: 14, lineHeight: 21, marginTop: 10, textAlign: 'center' },
  content: { paddingTop: 24 },
  toolbar: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 14 },
  count: { color: '#53666D', fontSize: 13 },
  createButton: { backgroundColor: '#409CB7', borderRadius: 10, minHeight: 42, justifyContent: 'center', paddingHorizontal: 15 },
  createButtonText: { color: '#FFFFFF', fontSize: 13, fontWeight: '700' },
  card: { backgroundColor: '#FFFFFF', borderRadius: 14, marginBottom: 12, padding: 16 },
  cardHeader: { alignItems: 'center', flexDirection: 'row' },
  cardTitle: { color: '#10161F', flex: 1, fontSize: 16, fontWeight: '700' },
  status: { borderRadius: 6, fontSize: 11, fontWeight: '700', marginLeft: 10, overflow: 'hidden', paddingHorizontal: 7, paddingVertical: 4 },
  published: { backgroundColor: '#EAF7FA', color: '#287D95' },
  draft: { backgroundColor: '#F0F2F3', color: '#6B7478' },
  cardContent: { color: '#59666B', fontSize: 13, lineHeight: 20, marginTop: 10 },
  cardDate: { color: '#8A9194', fontSize: 11, marginTop: 10 },
  actions: { borderTopColor: '#E7ECEE', borderTopWidth: 1, flexDirection: 'row', gap: 8, marginTop: 14, paddingTop: 12 },
  actionButton: { backgroundColor: '#F1F5F6', borderRadius: 8, flex: 1, minHeight: 38, justifyContent: 'center' },
  actionButtonText: { color: '#53666D', fontSize: 12, fontWeight: '700', textAlign: 'center' },
  deleteButton: { backgroundColor: '#FFF1F0' },
  deleteButtonText: { color: '#C74444' },
  message: { color: '#8A9194', fontSize: 14, paddingTop: 70, textAlign: 'center' },
  loadingMore: { paddingVertical: 18 },
  modalRoot: { backgroundColor: 'rgba(16, 22, 31, 0.38)', flex: 1, justifyContent: 'flex-end' },
  modalCard: { backgroundColor: '#FFFFFF', borderTopLeftRadius: 24, borderTopRightRadius: 24, maxHeight: '90%', padding: 22 },
  modalHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  modalTitle: { color: '#10161F', fontSize: 20, fontWeight: '700' },
  closeButton: { alignItems: 'center', height: 36, justifyContent: 'center', width: 36 },
  label: { color: '#53666D', fontSize: 12, fontWeight: '700', marginBottom: 6, marginTop: 16 },
  input: { borderColor: '#DCE5E8', borderRadius: 10, borderWidth: 1, color: '#10161F', fontSize: 15, minHeight: 44, paddingHorizontal: 12 },
  textArea: { minHeight: 150, paddingTop: 12, textAlignVertical: 'top' },
  modalActions: { flexDirection: 'row', gap: 10, marginTop: 22 },
  cancelButton: { backgroundColor: '#F1F5F6', borderRadius: 10, flex: 1, minHeight: 48, justifyContent: 'center' },
  cancelButtonText: { color: '#53666D', fontSize: 14, fontWeight: '700', textAlign: 'center' },
  saveButton: { backgroundColor: '#409CB7', borderRadius: 10, flex: 1, minHeight: 48, justifyContent: 'center' },
  saveButtonText: { color: '#FFFFFF', fontSize: 14, fontWeight: '700', textAlign: 'center' },
});
