// 프로필 화면에서 사용하는 스타일 모음입니다.
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    backgroundColor: '#F2F8FB',
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
  },
  accountPageContainer: {
    backgroundColor: '#FFFFFF',
    flex: 1,
  },
  accountPageHeader: {
    backgroundColor: '#FFFFFF',
  },
  profileSection: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    minHeight: 326,
  },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    height: 44,
    justifyContent: 'space-between',
    width: '100%',
  },
  iconButton: {
    alignItems: 'center',
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  headerTitle: {
    color: '#10161F',
    fontSize: 16,
    fontWeight: '600',
    letterSpacing: 0,
  },
  profileInfo: {
    alignItems: 'center',
    marginTop: 35,
  },
  avatarButton: {
    height: 110,
    position: 'relative',
    width: 110,
  },
  editBadge: {
    alignItems: 'center',
    backgroundColor: '#CECECE',
    borderRadius: 999,
    bottom: 5,
    height: 30,
    justifyContent: 'center',
    position: 'absolute',
    right: 0,
    width: 30,
  },
  username: {
    color: '#10161F',
    fontSize: 20,
    fontWeight: '600',
    letterSpacing: 0,
    marginTop: 15,
  },
  accountSummarySection: {
    paddingBottom: 28,
    paddingTop: 26,
  },
  accountLoadingState: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 260,
  },
  accountLoadingText: {
    color: '#8A9194',
    fontSize: 13,
    marginTop: 12,
  },
  accountSection: {
    marginBottom: 26,
    width: '100%',
  },
  accountCard: {
    backgroundColor: '#FFFFFF',
    width: '100%',
  },
  accountSectionTitle: {
    color: '#53666D',
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 9,
  },
  accountDetailRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 72,
    paddingVertical: 14,
  },
  accountRowLabel: {
    color: '#10161F',
    flexShrink: 1,
    fontSize: 16,
    fontWeight: '500',
  },
  accountRowValue: {
    color: '#10161F',
    flexShrink: 1,
    fontSize: 14,
    fontWeight: '600',
    marginLeft: 10,
    maxWidth: '58%',
    textAlign: 'right',
  },
  menuSection: {
    alignItems: 'center',
    paddingTop: 27,
  },
  menuCard: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    paddingHorizontal: 34,
    paddingVertical: 20,
    width: '100%',
  },
  menuRow: {
    alignItems: 'center',
    flexDirection: 'row',
    height: 75,
    justifyContent: 'space-between',
  },
  menuLeft: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 16,
  },
  menuText: {
    color: '#10161F',
    fontSize: 16,
    fontWeight: '500',
    letterSpacing: 0,
  },
  menuDivider: {
    backgroundColor: '#E7ECEE',
    height: 1,
    marginVertical: 8,
  },
  deleteAccountText: {
    color: '#C74444',
    fontSize: 16,
    fontWeight: '500',
    letterSpacing: 0,
  },
  modalBackdrop: {
    alignItems: 'center',
    backgroundColor: 'rgba(16, 22, 31, 0.38)',
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  languageModal: {
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    padding: 24,
    width: '100%',
  },
  deleteAccountModal: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    maxWidth: 390,
    padding: 24,
    width: '100%',
  },
  deleteAccountModalHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  deleteAccountIcon: {
    alignItems: 'center',
    backgroundColor: '#FFF1F0',
    borderRadius: 999,
    height: 46,
    justifyContent: 'center',
    width: 46,
  },
  deleteAccountModalTitle: {
    color: '#10161F',
    fontSize: 21,
    fontWeight: '700',
    letterSpacing: -0.3,
    marginTop: 17,
  },
  deleteAccountModalDescription: {
    color: '#59666B',
    fontSize: 13,
    lineHeight: 20,
    marginTop: 8,
  },
  deletedDataCard: {
    backgroundColor: '#F6FAFB',
    borderRadius: 14,
    marginTop: 17,
    paddingHorizontal: 15,
    paddingVertical: 13,
  },
  deletedDataTitle: {
    color: '#53666D',
    fontSize: 12,
    fontWeight: '700',
    marginBottom: 7,
  },
  deletedDataItem: {
    alignItems: 'center',
    flexDirection: 'row',
    minHeight: 25,
  },
  deletedDataBullet: {
    backgroundColor: '#7BAFBC',
    borderRadius: 999,
    height: 4,
    marginRight: 9,
    width: 4,
  },
  deletedDataText: {
    color: '#252B30',
    flex: 1,
    fontSize: 13,
    lineHeight: 19,
  },
  deleteAccountNotice: {
    color: '#8A9194',
    fontSize: 11,
    lineHeight: 17,
    marginTop: 12,
  },
  agreementRow: {
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: 17,
    minHeight: 28,
  },
  agreementText: {
    color: '#3E494D',
    flex: 1,
    fontSize: 12,
    lineHeight: 18,
    marginLeft: 8,
  },
  deleteAccountButtonRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 22,
  },
  cancelDeleteButton: {
    alignItems: 'center',
    backgroundColor: '#F1F5F6',
    borderRadius: 13,
    flex: 1,
    height: 50,
    justifyContent: 'center',
  },
  cancelDeleteButtonText: {
    color: '#53666D',
    fontSize: 14,
    fontWeight: '700',
  },
  confirmDeleteButton: {
    alignItems: 'center',
    backgroundColor: '#C74444',
    borderRadius: 13,
    flex: 1,
    height: 50,
    justifyContent: 'center',
  },
  disabledDeleteButton: {
    backgroundColor: '#E3B9B7',
  },
  confirmDeleteButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
  modalHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  modalTitle: {
    color: '#10161F',
    fontSize: 20,
    fontWeight: '700',
  },
  modalCloseButton: {
    alignItems: 'center',
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  modalDescription: {
    color: '#6E767B',
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 16,
    marginTop: 8,
  },
  languageOption: {
    alignItems: 'center',
    borderColor: '#E2E7E9',
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
    minHeight: 54,
    paddingHorizontal: 16,
  },
  selectedLanguageOption: {
    backgroundColor: '#F0FAFC',
    borderColor: '#409CB7',
  },
  languageOptionText: {
    color: '#252B30',
    fontSize: 16,
    fontWeight: '500',
  },
  selectedLanguageOptionText: {
    color: '#287D95',
    fontWeight: '700',
  },
});
