import { getPersistentAuthItem, setAuthItem, setPersistentAuthItem } from '@/lib/auth-storage';

export type AppLanguage = 'ko' | 'en';
export type TranslationParams = Record<string, string | number>;

export const DEFAULT_LANGUAGE: AppLanguage = 'ko';
const LANGUAGE_STORAGE_KEY = 'app_language';

const translations: Record<string, string> = {
  '가입된 이메일이 없습니다.': 'This email is not registered.',
  '입력하신 이메일로 가입된 계정을 찾을 수 없어요. 먼저 회원가입을 진행해 주세요.':
    'We couldn’t find an account with this email. Please sign up first.',
  '현재 기기에서 로그아웃할까요?': 'Log out on this device?',
  '계정을 탈퇴하면 프로필과 서비스 이용 정보가 삭제됩니다. 계속할까요?':
    'Deleting your account will remove your profile and service data. Continue?',
  '탈퇴 실패': 'Account deletion failed',
  '계정 탈퇴에 실패했습니다.': 'Failed to delete the account.',
  '비밀번호 변경': 'Change password',
  '비밀번호 변경하기': 'Change password',
  '비밀번호 재설정': 'Reset password',
  '비밀번호 재설정 요청': 'Password reset request',
  '인증 코드 받기': 'Get verification code',
  '비밀번호를 변경하려면 이메일 인증이 필요해요.': 'Email verification is required to change your password.',
  '이메일로 받은 인증 코드와 새 비밀번호를 입력해주세요.': 'Enter the verification code sent to your email and your new password.',
  '인증 코드를 이메일로 전송했어요.': 'A verification code has been sent to your email.',
  '인증 코드를 입력해주세요.': 'Enter the verification code.',
  '인증 코드는 6자리로 입력해주세요.': 'Enter the 6-digit verification code.',
  '인증 코드 6자리': '6-digit verification code',
  '새 비밀번호': 'New password',
  '새 비밀번호를 다시 입력해 주세요': 'Re-enter your new password',
  '모든 항목을 입력해주세요.': 'Please fill in all fields.',
  '올바른 이메일 형식으로 입력해 주세요.': 'Please enter a valid email address.',
  '비밀번호는 영문·숫자 포함 8자 이상이어야 합니다.': 'Password must be at least 8 characters with letters and numbers.',
  '비밀번호가 일치하지 않아요.': 'Passwords do not match.',
  '비밀번호가 변경되었어요. 새 비밀번호로 로그인해 주세요.':
    'Your password has been changed. Please log in with your new password.',
  '계정 탈퇴': 'Delete account',
  '개 미션으로 매거진 만들기': ' missions',
  '삭제': 'Delete',
  '날짜 미정': 'Date not set',
  '여행 목록 편집': 'Edit trip list',
  '여행 목록 편집 완료': 'Finish editing trip list',
  '표시할 미션이 없습니다.': 'No missions to display.',
  '확인 중': 'Checking',
  '담김': 'Saved',
  '담기': 'Save',
  '담을 날짜를 선택해 주세요': 'Select a date to save it',
  '담을 일정을 선택해 주세요': 'Select a schedule to save it',
  '일차를 선택해 주세요': 'Select a day',
  '미션 구 정보를 불러오지 못했습니다.': 'Could not load mission district information.',
  '장 제출 완료': ' photos submitted',
  '명까지 함께할 수 있어요.': ' people can join.',
  '년 ': ' ',
  '일': 'Sun',
  '월': 'Mon',
  '화': 'Tue',
  '수': 'Wed',
  '목': 'Thu',
  '금': 'Fri',
  '토': 'Sat',
  '일차에 하기': ' day',
  '님': '',
  '동행자를': 'Companions',
  '추가해 주세요': 'Please add them',
  '친구들이': 'Your friends',
  '카톡으로 여행갈 친구들을 모아보세요!': 'Invite friends to travel with you on KakaoTalk!',
  '거의 다 왔어요': 'Almost there',
  '다시 찍어보세요': 'Take another photo',
  '미션 인증 사진을 촬영하려면 카메라 접근을 허용해 주세요.': 'Allow camera access to take a mission photo.',
  '사진을 확인하고 있어요': 'Checking your photo',
  'AI가 미션 사진을 확인하고 있어요.': 'AI is checking your mission photo.',
  '이제 서로의 사진을 감상하고 댓글을 남겨보세요.': 'View each other’s photos and leave comments.',
  '프로필이미지를 골라보세요': 'Choose a profile image',
  '닉네임': 'Nickname',
  '우정 여행': 'Friend trip',
  '우정여행': 'Friend trip',
  '인증 코드': 'Verification code',
  '닉네임을 입력해 주세요.': 'Please enter a nickname.',
  '이메일 주소': 'Email address',
  '비밀번호': 'Password',
  '비밀번호를 다시 입력해 주세요': 'Re-enter your password',
  '영문, 숫자를 포함해 8자 이상': 'At least 8 characters with letters and numbers',
  '이전 달': 'Previous month',
  '다음 달': 'Next month',
  '닫기': 'Close',
  '돌아가기': 'Go back',
  '플래시': 'Flash',
  '사진 촬영': 'Take photo',
  '카메라 전환': 'Switch camera',
  '카메라로 미션 사진을 찍으면 여기에 보여요.': 'Mission photos taken with the camera will appear here.',
  '미션 날짜 변경': 'Change mission date',
  '일정 이름 지우기': 'Clear schedule name',
  '일정 선택 닫기': 'Close schedule selection',
  '담긴 미션 닫기': 'Close saved missions',
  '미션 시작 팝업 닫기': 'Close mission start popup',
  '초대 닫기': 'Close invitation',
  '초대 링크 복사하기': 'Copy invitation link',
  '댓글 보내기': 'Send comment',
  '미션 상세 리스트 열기': 'Open mission details',
  '미션 보기': 'View missions',
  '비활성 구': 'Inactive district',
  '미션 상세 보기': 'Mission details',
  '카카오 간편 로그인': 'Quick Kakao login',
  '카카오톡으로 초대하기': 'Invite via KakaoTalk',
  '앨범 또는 카메라에서 프로필 사진 선택': 'Choose a profile photo from your library or camera',
  '닉네임 지우기': 'Clear nickname',
  '프로필 이미지 선택 닫기': 'Close profile image selection',
  '프로필 이미지 선택': 'Choose profile image',
  '사진 가져오기': 'Get photo',
  '동행자 삭제': 'Remove companion',
  '일정 삭제': 'Delete schedule',
  '일정 만들기': 'Create schedule',
  '일정을 만드시겠습니까?': 'Would you like to create a schedule?',
  '일정을 만든 뒤 동행자를 초대할 수 있어요.': 'You can invite companions after creating a schedule.',
  '여행갈 친구들을 모아보세요!': 'Invite friends to travel with you!',
  '정말 삭제할까요?': 'Are you sure you want to delete it?',
  '간편 로그인': 'Quick login',
  '한국어': 'Korean',
  'English': 'English',
  '언어 설정': 'Language',
  '매거진 생성 및 조회에 사용할 언어를 선택해주세요.': 'Choose the language for creating and viewing magazines.',
  '산': 'Mountain',
  '바다': 'Sea',
  '도시': 'City',
  '데모': 'Demo',
  '테마별 미션을 확인해보세요': 'Explore missions by theme',
  '부산은 산과 바다, 도심이 아우러진\n15개 구와 1개 군으로 구성되어 있습니다.':
    'Busan brings together mountains, sea, and city life,\nwith 15 districts and 1 county.',
  '획득': 'Acquired',
  '부산': 'Busan',
  '넘겨서 다음 미션 보기': 'Swipe to view the next mission',
  '새 일정 만들기': 'Create a new schedule',
  '새 일정 만들기로 여행을 시작해보세요.': 'Start your trip by creating a new schedule.',
  '여행 날짜와 동행자를 설정해요': 'Set your trip dates and companions',
  '개인정보 / 보안': 'Privacy / Security',
  '관광지 검색': 'Search attractions',
  '관광지를 검색해주세요...': 'Search for a place...',
  '검색어 지우기': 'Clear search query',
  '관광지': 'Attractions',
  '문화시설': 'Cultural facilities',
  '축제·행사': 'Festivals & events',
  '여행코스': 'Travel courses',
  '레포츠': 'Leisure',
  '숙박': 'Accommodation',
  '쇼핑': 'Shopping',
  '부산 지역의 관광 정보를 확인해보세요.': 'Explore tourist information in Busan.',
  '부산 관광지': 'Busan attractions',
  '상세 정보': 'Details',
  '관광지 검색에 실패했어요.': 'Could not search for tourist attractions.',
  '검색 결과가 없습니다.': 'No search results.',
  '최근 검색어': 'Recent searches',
  '전체 삭제': 'Clear all',
  '최근 검색어가 없습니다': 'There are no recent searches.',
  '추천 검색어': 'Recommended searches',
  '부산 맛집 투어': 'Busan food tour',
  '커플 여행코스': "Couples' travel course",
  '가족과 함께': 'With family',
  '아이들이 좋아하는': 'Kid-friendly',
  '바다 근처': 'Near the sea',
  '관광지 상세': 'Attraction details',
  '소개': 'Overview',
  '행사': 'Events',
  '같이 보면 좋은 ': 'Good to see ',
  '주변 행사': 'nearby events',
  '이곳에 어울리는 ': 'Recommended ',
  '추천순  ·  거리순': 'Recommended  ·  By distance',
  '현재 등록된 주변 행사가 없어요.': 'There are no nearby events currently listed.',
  '이 장소에 어울리는 미션이 아직 없어요.': 'There are no missions for this place yet.',
  '반려동물과 함께하기 좋은 곳': 'A pet-friendly place',
  '반려동물 동반 정보를 확인해보세요.': 'Check the pet access information.',
  '관광지 정보를 찾을 수 없어요.': 'Could not find the tourist attraction.',
  '관광지 정보를 불러오지 못했어요.': 'Could not load the tourist attraction.',
  '주변 행사 정보를 불러오지 못했어요.': 'Could not load nearby event information.',
  '미션명': 'Mission name',
  '검색어를 입력해주세요.': 'Please enter a search term.',
  '검색어는 100자 이내로 입력해주세요.': 'Search terms must be 100 characters or fewer.',
  '복사': 'Copy',
  '담음': 'Saved',
  '아직 만든 일정이 없어요.': 'You have no schedules yet.',
  '아직 만든 일정이 없어요. 일정을 만드시겠습니까?': 'You have no schedules yet. Would you like to create one?',
  '네': 'Yes',
  '예': 'Yes',
  '아니요': 'No',
  '여행 수정': 'Edit trip',
  '기간': 'Dates',
  '추가': 'Add',
  '담아둔 미션이 없어요.': 'There are no saved missions.',
  '순서 수정': 'Edit order',
  '아직 담긴 미션이 없어요.': 'There are no saved missions yet.',
  '위치': 'Location',
  '여행 위치 기록과 주변 장소 추천을 위해 사용합니다.':
    'Used to record your travel locations and recommend nearby places.',
  '카메라': 'Camera',
  '미션 사진을 촬영하기 위해 사용합니다.': 'Used to take mission photos.',
  '위치기반서비스 이용약관': 'Location-Based Services Terms',
  '개인정보처리방침': 'Privacy Policy',
  '서비스 이용약관': 'Terms of Service',
  '내 개인정보 열람': 'View my personal information',
  '개인정보 열람 요청 기능은 서버 API 연결 후 사용할 수 있습니다.':
    'The request to view personal information will be available after the server API is connected.',
  '동의 철회': 'Withdraw consent',
  '동의 철회 기능은 서버 API 연결 후 사용할 수 있습니다.':
    'The consent withdrawal feature will be available after the server API is connected.',
  '약관을 불러오지 못했습니다. 잠시 후 다시 시도해 주세요.': 'Could not load the terms. Please try again later.',
  '설정 열기 실패': 'Could not open settings',
  '휴대폰 설정에서 앱 권한을 직접 변경해 주세요.': 'Please change the app permissions directly in your phone settings.',
  '권한이 필요합니다': 'Permission required',
  '권한을 변경하려면 휴대폰 설정에서 허용해 주세요.': 'To change permissions, allow access in your phone settings.',
  '취소': 'Cancel',
  '설정 열기': 'Open settings',
  '권한 요청 실패': 'Permission request failed',
  '잠시 후 다시 시도해 주세요.': 'Please try again later.',
  '권한 관리': 'Manage permissions',
  '권한을 끄려면 휴대폰 설정에서 변경해 주세요.': 'To turn off the permission, change it in your phone settings.',
  '약관 및 정책': 'Terms and policies',
  '약관을 불러오는 중입니다.': 'Loading terms.',
  '앱 권한': 'App permissions',
  '내 데이터 관리': 'Manage my data',
  '켜짐': 'On',
  '꺼짐': 'Off',
  '알림 설정': 'Notification settings',
  '알림 수신': 'Notifications',
  '미션 알림': 'Mission notifications',
  '매거진 알림': 'Magazine notifications',
  '공지 알림': 'Announcement notifications',
  '전체 알림을 한 번에 설정할 수 있어요.': 'Manage all notifications at once.',
  '알림 유형': 'Notification types',
  '추가 수신 동의': 'Additional notification consent',
  '필수': 'Required',
  '이벤트, 혜택 및 프로모션 소식을 받아요.': 'Receive news about events, benefits, and promotions.',
  '야간 알림 수신 동의': 'Consent to receive nighttime notifications',
  '21:00 ~ 08:00에도 알림을 받을 수 있어요.': 'You may receive notifications from 21:00 to 08:00.',
  '야간 알림은 오전 8시에 알려드려요.': 'Nighttime notifications will be sent at 8:00 AM.',
  '휴대폰 알림 설정': 'Phone notification settings',
  '마케팅 알림 수신 동의': 'Consent to receive marketing notifications',
  '휴대폰 알림 권한': 'Phone notification permission',
  '현재 알림이 허용되어 있어요.': 'Notifications are currently allowed.',
  '알림 권한 필요': 'Notification permission required',
  'Expo Go에서는 시스템 알림을 사용할 수 없습니다. development build에서 알림 권한을 허용해주세요.':
    'System notifications are not available in Expo Go. Please allow notification permissions in a development build.',
  '비밀번호를 입력해 주세요': 'Please enter a password',
  '비밀번호가 일치해요': 'Passwords match',
  '비밀번호가 일치하지 않아요': 'Passwords do not match',
  '결과 보기': 'View results',
  '계속하기': 'Continue',
  '권한 허용': 'Allow permission',
  '그룹에 들어갈 수 없어요': 'You cannot join this group.',
  '기본 미션': 'Basic mission',
  '날짜별 경로': 'Routes by date',
  '미션 순서를 추천받아 보세요': 'Get a recommended mission order',
  '경로 생성': 'Create route',
  '경로 생성 완료': 'Route created',
  '생성 완료': 'Created',
  '추천 중': 'Recommending',
  '동선 추천에 실패했습니다. 잠시 후 다시 시도해 주세요.': 'Route recommendation failed. Please try again later.',
  '날짜 선택': 'Select a date',
  '날짜별 담긴 미션': 'Missions by date',
  '다음': 'Next',
  '다시 시도': 'Try again',
  '다시 찍기': 'Retake',
  '담긴 미션 없음': 'No saved missions',
  '담긴 미션을 불러오는 중이에요.': 'Loading saved missions.',
  '담아둔 미션을 일정별로 관리해 보세요.': 'Manage your saved missions by schedule.',
  '댓글 등록에 실패했어요.': 'Failed to post the comment.',
  '댓글 시간이 종료됐어요.': 'The comment period has ended.',
  '댓글을 남겨주세요...': 'Leave a comment...',
  '동행자': 'Companion',
  '동행자 추가': 'Add companion',
  '동행자 추가 권한이 없습니다.': 'You do not have permission to add companions.',
  '동행자 추가하기': 'Add companions',
  '뒤로 가기': 'Go back',
  '뒤로가기': 'Go back',
  '로그인': 'Log in',
  '로그아웃': 'Log out',
  '링크 복사하기': 'Copy link',
  '마감된 일정': 'Closed schedule',
  '매거진': 'Magazine',
  '매거진 생성에 실패했어요.': 'Failed to create the magazine.',
  '매거진을 만들고 있어요.': 'Creating your magazine.',
  '매거진을 불러오는 중이에요.': 'Loading your magazine.',
  '매거진에 넣을 미션을 선택해주세요': 'Select missions for your magazine',
  '매거진에 넣을 수 있는 완료 미션 사진이 아직 없어요.': 'There are no completed mission photos for a magazine yet.',
  '멤버': 'Member',
  '미션': 'Mission',
  '미션 상세 리스트': 'Mission details',
  '미션 상세 리스트에서 원하는 미션을 담아보세요.': 'Add a mission from the mission details.',
  '미션을 불러오는 중': 'Loading missions',
  '미션을 불러오는 중입니다.': 'Loading missions.',
  '미션을 추가할 수 있는 일정이 없어요.': 'There are no schedules to add a mission to.',
  '미션을 추가할 수 없습니다.': 'Cannot add the mission.',
  '미션을 일정에 담지 못했어요.': 'Could not add the mission to the schedule.',
  '미션을 삭제할 수 없습니다.': 'Cannot delete the mission.',
  '미션을 시작하지 못했어요.': 'Could not start the mission.',
  '미션 설명이 아직 없습니다.': 'Mission description is not available yet.',
  '미션 설명을 확인하고 다시 촬영해 주세요.': 'Check the mission instructions and take the photo again.',
  '미션 참여': 'Join mission',
  '미션장이 자동으로 참여돼요.': 'The mission leader joins automatically.',
  '미션장이 참여자를 확인한 뒤 시작해요.': 'The mission leader will start after checking participants.',
  '미션추가': 'Add mission',
  '미션에 맞게 다시 찍어보세요': 'Take another photo that matches the mission',
  '미션 정보가 없습니다.': 'Mission information is unavailable.',
  '미션 정보를 불러오는 중입니다.': 'Loading mission information.',
  '미션 정보를 찾지 못했어요.': 'Could not find the mission information.',
  '미션을 선택해주세요.': 'Please select a mission.',
  '미션 삭제': 'Delete mission',
  '미션 시작하기': 'Start mission',
  '미션 완료!': 'Mission complete!',
  '미션 완료 알림 닫기': 'Close mission completion alert',
  '미션 장소 근처에서만 참여할 수 있어요.': 'You can only participate near the mission location.',
  '미션에 참여할 사람을 확인하고 있어요.': 'Checking who will participate in this mission.',
  '미션에 넣을 미션을 선택해주세요': 'Select missions to include',
  '모두 댓글 작성을 완료했어요!': 'Everyone has finished commenting!',
  '목록으로 돌아가기': 'Back to list',
  '사진을 확인하고 있어요.': 'Checking your photo.',
  '사진을 확인해 주세요': 'Please check your photo',
  '사진 찍기 미션 완료!': 'Photo mission complete!',
  '사진 업로드': 'Upload photo',
  '사진 업로드 응답이 지연되고 있어요. 네트워크를 확인하고 다시 시도해 주세요.': 'The photo upload is taking longer than expected. Check your network and try again.',
  '사진이 매거진에 담겨요': 'This photo will be included in the magazine.',
  '사진을 가져올 방법을 선택해주세요.': 'Choose how to get a photo.',
  '선택': 'Select',
  '선택 대기': 'Waiting for selection',
  '선택할 수 있는 날짜가 없어요.': 'There are no available dates.',
  '선택한 날짜가 없습니다.': 'No date selected.',
  '서버에서 세션을 불러오는 중이에요.': 'Loading the session from the server.',
  '설정': 'Settings',
  '수정 완료': 'Done',
  '시작할 수 없어요': 'Cannot start',
  '아직 공개된 사진이 없어요.': 'No photos have been revealed yet.',
  '아직 댓글이 없어요': 'There are no comments yet.',
  '아직 담긴 미션이 없어요': 'There are no saved missions yet.',
  '아직 만든 일정이 없어요': 'You have no schedules yet.',
  '아직 찍은 사진이 없어요': 'There are no photos yet.',
  '알림': 'Notifications',
  '앨범에서 선택': 'Choose from library',
  '업로드하기': 'Upload',
  '완료': 'Done',
  '완료하기': 'Finish',
  '여행 목록': 'Trips',
  '여행 목록으로': 'Back to trips',
  '여행 설정': 'Trip settings',
  '여행 시작': 'Start trip',
  '여행 시작하기': 'Start your trip',
  '여행 기간 정하기': 'Set trip dates',
  '여행 기간을 선택해 주세요.': 'Please select the trip dates.',
  '여행 날짜 미정': 'Trip dates not set',
  '여행 종료': 'Trip ended',
  '여행을 떠나볼까요?': 'Ready for a trip?',
  '여행 일정': 'Trip schedule',
  '여행 일정 삭제': 'Delete trip schedule',
  '여행 일정을 불러오지 못했습니다.': 'Could not load trip schedules.',
  '오늘': 'Today',
  '오늘 · 여행': 'Today · Trip',
  '이메일 로그인': 'Email login',
  '이메일 인증': 'Email verification',
  '이메일로 받은 인증 코드를 입력해주세요.': 'Enter the verification code sent to your email.',
  '이미 담긴 미션이에요. 날짜 변경이나 삭제는 일정 화면에서 할 수 있어요.': 'This mission is already saved. Change its date or delete it from the schedule screen.',
  '이미 시작한 미션이 있어 동행자를 추가할 수 없어요.': 'You cannot add companions after a mission has started.',
  '입장하기': 'Join',
  '일정 관리': 'Manage schedules',
  '일정 다시 선택': 'Choose another schedule',
  '일정 이름': 'Schedule name',
  '일정 이름을 입력해 주세요.': 'Please enter a schedule name.',
  '일정 이름을 작성해주세요': 'Enter a schedule name',
  '일정이 없습니다.': 'No schedule is available.',
  '자동 로그인': 'Stay logged in',
  '저장하기': 'Save',
  '저장된 미션': 'Saved missions',
  '저장할 수 없습니다.': 'Cannot save.',
  '지우기': 'Remove',
  '진행 중': 'In progress',
  '진행 중인 미션을 먼저 완료해주세요.': 'Please finish the mission in progress first.',
  '진행 중인 미션은 날짜를 바꿀 수 없어요.': 'The date cannot be changed while a mission is in progress.',
  '진행 중인 미션은 삭제할 수 없어요.': 'A mission in progress cannot be deleted.',
  '처음이신가요?': 'First time here?',
  '초대 확인 실패': 'Invitation check failed',
  '초대 완료': 'Invitation accepted',
  '초대장을 만들지 못했어요.': 'Could not create the invitation.',
  '카카오 계정': 'Kakao account',
  '카카오톡': 'KakaoTalk',
  '카카오로 계속하기': 'Continue with Kakao',
  '카메라 권한이 필요해요': 'Camera permission is required',
  '카메라 접근을 허용해 주세요.': 'Please allow camera access.',
  '패스할게요': 'I will pass',
  '프로필': 'Profile',
  '프로필 사진': 'Profile photo',
  '프로필 사진 변경': 'Change profile photo',
  '프로필 편집': 'Edit profile',
  '확인': 'OK',
  '확인하러 가기': 'View it',
  '회원가입': 'Sign up',
  '회원가입하기': 'Sign up',
  '희귀 미션': 'Rare mission',
  '사이드 미션': 'Side mission',
  '반가워요! 여행을 시작할까요?': 'Welcome! Ready to start a trip?',
  '어떤 여행인가요?': 'What kind of trip is this?',
  '여행 기간에 맞춰 미션이 부여돼요.': 'Missions are assigned based on your trip dates.',
  '여행 기간을 알려주세요': 'Tell us your trip dates',
  '친구들이 가장 많이 선택한 사진': 'The photo your friends chose most',
  '친구가 담은 사진이에요': 'This is a photo your friend selected.',
  '당신의 선택은?': 'Which one do you choose?',
  '이번 미션을 대표할 사진을 골라주세요.': 'Choose the photo that represents this mission.',
  '이번 미션의 주인공은?': 'Who is the star of this mission?',
  '친구들의 선택이 모였어요.': 'Your friends have voted.',
  '가장 많은 선택을 받은 사진을 공개할게요.': 'We will reveal the most-voted photo.',
  '익명으로 한마디 남겨보세요.': 'Leave an anonymous comment.',
  '다른 댓글을 기다리는 중이에요.': 'Waiting for another comment.',
  '참여할게요': 'I will join',
  '현재 참여자': 'Current participants',
  '이번 미션에 참여할 사람을 확인하고 있어요.': 'Checking who will join this mission.',
  '촬영 화면을 준비하고 있어요.': 'Preparing the camera screen.',
  '매거진 저장/공유': 'Save/share magazine',
  '튜토리얼 완료하고 메인으로': 'Finish tutorial and go to home',
  '첫 번째 매거진을 기다리고 있어요': 'Waiting for your first magazine',
  '여행을 완료하면 이곳에서 매거진을 확인할 수 있어요.': 'Complete a trip to view your magazine here.',
  '미션 리스트': 'Mission list',
};

let currentLanguage: AppLanguage = DEFAULT_LANGUAGE;

function isAppLanguage(value: string | null | undefined): value is AppLanguage {
  return value === 'ko' || value === 'en';
}

export function getCurrentLanguage(): AppLanguage {
  return currentLanguage;
}

export function setCurrentLanguage(language: AppLanguage) {
  currentLanguage = language;
  setAuthItem(LANGUAGE_STORAGE_KEY, language);
}

export async function loadSavedLanguage() {
  const savedLanguage = await getPersistentAuthItem(LANGUAGE_STORAGE_KEY);

  if (isAppLanguage(savedLanguage)) {
    currentLanguage = savedLanguage;
  }

  return currentLanguage;
}

export function getLanguageHeaders(language: AppLanguage = getCurrentLanguage()) {
  return { 'Accept-Language': language };
}

export function translateText(value: string, params: TranslationParams = {}) {
  if (getCurrentLanguage() === 'ko') {
    return value;
  }

  let translated = translations[value] ?? value;

  if (translated === value) {
    const englishMonthNames = [
      'January',
      'February',
      'March',
      'April',
      'May',
      'June',
      'July',
      'August',
      'September',
      'October',
      'November',
      'December',
    ];
    const patterns: [RegExp, (match: RegExpMatchArray) => string][] = [
      [/^(\d{4})년 (\d{1,2})월$/, (match) => `${englishMonthNames[Number(match[2]) - 1]} ${match[1]}`],
      [/^(\d{1,2})월 (\d{1,2})일$/, (match) => `${englishMonthNames[Number(match[1]) - 1]} ${match[2]}`],
      [/^(\d{4})년 (\d{1,2})월 (\d{1,2})일$/, (match) => `${englishMonthNames[Number(match[2]) - 1]} ${match[3]}, ${match[1]}`],
      [/^(\d+)일차$/, (match) => `Day ${match[1]}`],
      [/^(.+) 일정을 삭제할까요\?$/, (match) => `Delete the "${match[1]}" schedule?`],
      [/^(\d+)개 미션으로 매거진 만들기$/, (match) => `Create a magazine with ${match[1]} missions`],
      [/^최대 (\d+)개까지 선택할 수 있어요\.$/, (match) => `You can select up to ${match[1]} missions.`],
      [/^(\d+)개$/, (match) => `${match[1]}`],
      [/^(\d+)명$/, (match) => `${match[1]} people`],
      [/^총 (\d+)명까지 함께할 수 있어요\.$/, (match) => `Up to ${match[1]} people can join.`],
      [/^(\d+)일간 여행$/, (match) => `${match[1]}-day trip`],
      [/^(\d+)일차에 하기$/, (match) => `Do it on day ${match[1]}`],
      [/^오늘 · 여행 (\d+)일차$/, (match) => `Today · Day ${match[1]}`],
      [/^(\d+)초 뒤 결과를 보여드릴게요\.$/, (match) => `The result will be shown in ${match[1]} seconds.`],
      [/^(\d+)초 뒤 다음 사진으로 넘어가요!$/, (match) => `Moving to the next photo in ${match[1]} seconds!`],
      [/^사진 (\d+)장 제출 완료$/, (match) => `${match[1]} photos submitted`],
      [/^멤버 (\d+)$/, (match) => `Member ${match[1]}`],
      [/^(.+)님이 함께 여행하자고 초대했어요\.$/, (match) => `${match[1]} invited you to travel together.`],
      [/^(.+)님이 담았어요$/, (match) => `${match[1]} selected this photo`],
      [/^(.+) 미션을 일정에서 삭제할까요\?$/, (match) => `Remove ${match[1]} from the schedule?`],
      [/^(.+) 미션을 삭제했어요\.$/, (match) => `${match[1]} was removed from the schedule.`],
      [/^(.+) 미션 날짜를 (.+)로 바꿨어요\.$/, (match) => `${match[1]} mission date changed to ${match[2]}.`],
    ];

    patterns.push(
      [/^(.+) 검색어 삭제$/, (match) => `Delete search term "${match[1]}"`],
      [/^(.+) 소개$/, (match) => `${match[1]} overview`],
    );

    const matched = patterns.find(([pattern]) => pattern.test(value));
    if (matched) {
      translated = matched[1](value.match(matched[0]) as RegExpMatchArray);
    }
  }

  return Object.entries(params).reduce(
    (result, [key, parameter]) => result.replaceAll(`{{${key}}}`, String(parameter)),
    translated,
  );
}

export function persistLanguage(language: AppLanguage) {
  setCurrentLanguage(language);
  return setPersistentAuthItem(LANGUAGE_STORAGE_KEY, language);
}
