// 검색 화면에서 사용하는 스타일 모음입니다.
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    backgroundColor: '#FFFFFF',
    flex: 1,
    paddingHorizontal: 16,
  },
  title: {
    color: '#10161F',
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 25,
  },
  searchField: {
    alignItems: 'center',
    backgroundColor: '#F6F6F6',
    borderRadius: 28,
    flexDirection: 'row',
    height: 52,
    marginTop: 40,
    paddingHorizontal: 28,
  },
  input: {
    color: '#10161F',
    flex: 1,
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 22,
    marginLeft: 10,
    paddingVertical: 0,
  },
  clearButton: {
    alignItems: 'center',
    backgroundColor: '#92999B',
    borderRadius: 999,
    height: 22,
    justifyContent: 'center',
    width: 22,
  },
  content: {
    paddingBottom: 40,
  },
  recentHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 39,
  },
  sectionTitle: {
    color: '#10161F',
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 24,
  },
  deleteAll: {
    color: '#8A9194',
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 20,
  },
  emptyRecent: {
    color: '#8A9194',
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 18,
    marginTop: 41,
    textAlign: 'center',
  },
  chipList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 14,
  },
  recentChip: {
    alignItems: 'center',
    borderColor: '#D9E0E3',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 9,
    minHeight: 36,
    paddingHorizontal: 12,
  },
  recentChipPressable: {
    alignItems: 'center',
    flexDirection: 'row',
    minHeight: 34,
  },
  recentChipText: {
    color: '#10161F',
    fontSize: 12,
    fontWeight: '500',
  },
  recommendedTitle: {
    marginTop: 70,
  },
  recommendedChip: {
    alignItems: 'center',
    backgroundColor: '#EAF4F9',
    borderRadius: 18,
    minHeight: 36,
    paddingHorizontal: 14,
  },
  recommendedChipText: {
    color: '#659AB3',
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 36,
  },
  resultsContent: {
    gap: 18,
    paddingBottom: 30,
    paddingTop: 44,
  },
  resultCard: {
    backgroundColor: '#F7FAFC',
    borderRadius: 17,
    minHeight: 237,
    paddingHorizontal: 26,
    paddingVertical: 25,
  },
  resultHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  resultHeading: {
    flex: 1,
    paddingTop: 1,
  },
  resultTitle: {
    color: '#10161F',
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 23,
  },
  resultLocation: {
    color: '#10161F',
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 22,
    marginTop: 1,
  },
  resultImage: {
    backgroundColor: '#DDEBF2',
    borderRadius: 8,
    height: 77,
    width: 113,
  },
  resultImagePlaceholder: {
    backgroundColor: '#DDEBF2',
    borderRadius: 8,
    height: 77,
    width: 113,
  },
  resultDescription: {
    color: '#8A9194',
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 18,
    marginTop: 23,
  },
  resultTags: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    marginTop: 14,
  },
  resultTag: {
    alignItems: 'center',
    backgroundColor: '#C9E4EE',
    borderRadius: 18,
    flexDirection: 'row',
    gap: 6,
    minHeight: 35,
    paddingHorizontal: 12,
  },
  resultTagText: {
    color: '#2F7F9A',
    fontSize: 12,
    fontWeight: '500',
  },
  searchMessage: {
    color: '#8A9194',
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 18,
    paddingHorizontal: 12,
    paddingTop: 48,
    textAlign: 'center',
  },
  loadingState: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'flex-start',
    paddingTop: 48,
  },
  errorState: {
    flex: 1,
  },
  loadingMore: {
    paddingVertical: 12,
  },
});
