// 검색 화면에서 사용하는 스타일 모음입니다.
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    backgroundColor: '#FFFFFF',
    flex: 1,
    paddingHorizontal: 16,
  },
  title: {
    color: '#10161F',
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 25,
  },
  searchField: {
    alignItems: 'center',
    backgroundColor: '#F6F6F6',
    borderRadius: 28,
    flexDirection: 'row',
    height: 52,
    marginTop: 40,
    paddingHorizontal: 28,
  },
  input: {
    color: '#10161F',
    flex: 1,
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 22,
    marginLeft: 10,
    paddingVertical: 0,
  },
  clearButton: {
    alignItems: 'center',
    backgroundColor: '#92999B',
    borderRadius: 999,
    height: 22,
    justifyContent: 'center',
    width: 22,
  },
  typeSelector: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 14,
  },
  typeChip: {
    borderColor: '#D9E0E3',
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  typeChipSelected: {
    backgroundColor: '#E5F2F8',
    borderColor: '#74B1C9',
  },
  typeChipText: {
    color: '#8A9194',
    fontSize: 11,
    fontWeight: '500',
    lineHeight: 16,
  },
  typeChipTextSelected: {
    color: '#4C88A4',
    fontWeight: '600',
  },
  content: {
    paddingBottom: 40,
  },
  recentHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 39,
  },
  sectionTitle: {
    color: '#10161F',
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 24,
  },
  deleteAll: {
    color: '#8A9194',
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 20,
  },
  emptyRecent: {
    color: '#8A9194',
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 18,
    marginTop: 41,
    textAlign: 'center',
  },
  chipList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 14,
  },
  recentChip: {
    alignItems: 'center',
    borderColor: '#D9E0E3',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 9,
    minHeight: 36,
    paddingHorizontal: 12,
  },
  recentChipPressable: {
    alignItems: 'center',
    flexDirection: 'row',
    minHeight: 34,
  },
  recentChipText: {
    color: '#10161F',
    fontSize: 12,
    fontWeight: '500',
  },
  recommendedTitle: {
    marginTop: 70,
  },
  recommendedChip: {
    alignItems: 'center',
    backgroundColor: '#EAF4F9',
    borderRadius: 18,
    minHeight: 36,
    paddingHorizontal: 14,
  },
  recommendedChipText: {
    color: '#659AB3',
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 36,
  },
  resultsContent: {
    gap: 18,
    paddingBottom: 30,
    paddingTop: 44,
  },
  resultCard: {
    backgroundColor: '#F7FAFC',
    borderRadius: 17,
    minHeight: 237,
    paddingHorizontal: 26,
    paddingVertical: 25,
  },
  resultHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  resultHeading: {
    flex: 1,
    paddingTop: 1,
  },
  resultTitle: {
    color: '#10161F',
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 23,
  },
  resultLocation: {
    color: '#10161F',
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 22,
    marginTop: 1,
  },
  resultImage: {
    backgroundColor: '#DDEBF2',
    borderRadius: 8,
    height: 77,
    width: 113,
  },
  resultImagePlaceholder: {
    backgroundColor: '#DDEBF2',
    borderRadius: 8,
    height: 77,
    width: 113,
  },
  resultDescription: {
    color: '#8A9194',
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 18,
    marginTop: 23,
  },
  resultTags: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    marginTop: 14,
  },
  resultTag: {
    alignItems: 'center',
    backgroundColor: '#C9E4EE',
    borderRadius: 18,
    flexDirection: 'row',
    gap: 6,
    minHeight: 35,
    paddingHorizontal: 12,
  },
  resultTagText: {
    color: '#2F7F9A',
    fontSize: 12,
    fontWeight: '500',
  },
  searchMessage: {
    color: '#8A9194',
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 18,
    paddingHorizontal: 12,
    paddingTop: 48,
    textAlign: 'center',
  },
  loadingState: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'flex-start',
    paddingTop: 48,
  },
  errorState: {
    flex: 1,
  },
  loadingMore: {
    paddingVertical: 12,
  },
  placeDetailHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    height: 44,
    justifyContent: 'space-between',
  },
  placeDetailBackButton: {
    alignItems: 'center',
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  placeDetailHeaderTitle: {
    color: '#10161F',
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 24,
  },
  detailHeaderSpacer: {
    height: 40,
    width: 40,
  },
  detailContent: {
    paddingBottom: 40,
    paddingTop: 16,
  },
  detailImage: {
    backgroundColor: '#DDEBF2',
    borderRadius: 16,
    height: 210,
    width: '100%',
  },
  detailImagePlaceholder: {
    backgroundColor: '#DDEBF2',
    borderRadius: 16,
    height: 210,
    width: '100%',
  },
  detailTitle: {
    color: '#10161F',
    fontSize: 24,
    fontWeight: '600',
    lineHeight: 31,
    marginTop: 22,
  },
  detailAddress: {
    color: '#8A9194',
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 22,
    marginTop: 3,
  },
  detailPhone: {
    color: '#659AB3',
    fontSize: 13,
    fontWeight: '500',
    lineHeight: 20,
    marginTop: 5,
  },
  legacyDetailSectionTitle: {
    color: '#10161F',
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 24,
    marginTop: 32,
  },
  detailOverview: {
    color: '#596268',
    fontSize: 13,
    fontWeight: '500',
    lineHeight: 21,
    marginTop: 12,
  },
  petInfoCard: {
    backgroundColor: '#F7FAFC',
    borderRadius: 14,
    marginTop: 12,
    paddingHorizontal: 16,
    paddingVertical: 6,
  },
  petInfoRow: {
    borderBottomColor: '#E8EEF1',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 12,
    paddingVertical: 11,
  },
  petInfoLabel: {
    color: '#8A9194',
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 19,
    width: 88,
  },
  petInfoValue: {
    color: '#303941',
    flex: 1,
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 19,
  },
  missionRecommendationList: {
    gap: 14,
    marginTop: 12,
  },
  missionRecommendationCard: {
    backgroundColor: '#F7FAFC',
    borderRadius: 16,
    paddingHorizontal: 18,
    paddingVertical: 18,
  },
  missionRecommendationHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  missionRecommendationHeading: {
    flex: 1,
    paddingRight: 12,
  },
  missionRecommendationTitle: {
    color: '#10161F',
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 23,
  },
  missionRecommendationPlace: {
    color: '#596268',
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 19,
    marginTop: 3,
  },
  missionRecommendationDistance: {
    color: '#659AB3',
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 19,
    marginTop: 2,
  },
  missionRecommendationImage: {
    backgroundColor: '#DDEBF2',
    borderRadius: 8,
    height: 76,
    width: 110,
  },
  missionRecommendationImagePlaceholder: {
    backgroundColor: '#DDEBF2',
    borderRadius: 8,
    height: 76,
    width: 110,
  },
  missionRecommendationDescription: {
    color: '#596268',
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 19,
    marginTop: 16,
  },
  matchReasons: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 7,
    marginTop: 13,
  },
  matchReason: {
    backgroundColor: '#E5F2F8',
    borderRadius: 15,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  matchReasonText: {
    color: '#659AB3',
    fontSize: 11,
    fontWeight: '500',
    lineHeight: 16,
  },
  detailLoadingState: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
  },
  detailMessageState: {
    flex: 1,
  },
  detailScreenContainer: {
    backgroundColor: '#FFFFFF',
    flex: 1,
  },
  detailTopSection: {
    backgroundColor: '#FFFFFF',
  },
  detailPageHeader: {
    backgroundColor: 'transparent',
    paddingBottom: 20,
    paddingHorizontal: 16,
  },
  detailPageBackButton: {
    alignItems: 'flex-start',
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  detailHeading: {
    marginTop: 15,
    paddingLeft: 0,
    paddingRight: 0,
  },
  detailPageHeaderTitle: {
    color: '#10161F',
    fontSize: 24,
    fontWeight: '600',
    lineHeight: 37,
  },
  detailHeaderAddress: {
    color: '#8A9194',
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 22,
    marginTop: 1,
  },
  tabBar: {
    backgroundColor: 'rgba(255, 255, 255, 0.82)',
    borderBottomColor: '#D9E0E3',
    borderBottomWidth: 1,
    flexDirection: 'row',
    height: 54,
  },
  tab: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    position: 'relative',
  },
  tabText: {
    color: '#10161F',
    fontSize: 14,
    fontWeight: '500',
  },
  tabTextActive: {
    fontWeight: '700',
  },
  tabIndicator: {
    backgroundColor: '#000000',
    bottom: -1,
    height: 2,
    position: 'absolute',
    width: 26,
  },
  pagerContent: {
    paddingBottom: 40,
  },
  detailSection: {
    paddingHorizontal: 16,
    width: '100%',
  },
  introSection: {
    backgroundColor: '#FFFFFF',
    paddingBottom: 42,
    paddingTop: 42,
  },
  introImage: {
    aspectRatio: 1.5,
    backgroundColor: '#DDEBF2',
    borderRadius: 16,
    width: '100%',
  },
  introImagePlaceholder: {
    aspectRatio: 1.5,
    backgroundColor: '#DDEBF2',
    borderRadius: 16,
    width: '100%',
  },
  introTitle: {
    color: '#10161F',
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 27,
    marginTop: 22,
  },
  introOverview: {
    color: '#6D7477',
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 24,
    marginTop: 14,
  },
  tagList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 17,
  },
  placeTag: {
    backgroundColor: '#E3F0F6',
    borderRadius: 50,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  placeTagText: {
    color: '#409CB7',
    fontSize: 12,
    fontWeight: '500',
  },
  petSummary: {
    backgroundColor: '#F7FAFC',
    borderRadius: 14,
    marginTop: 18,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  petSummaryTitle: {
    color: '#10161F',
    fontSize: 14,
    fontWeight: '600',
  },
  petSummaryText: {
    color: '#596268',
    fontSize: 12,
    lineHeight: 19,
    marginTop: 5,
  },
  eventSection: {
    backgroundColor: '#E3F0F6',
    paddingBottom: 44,
    paddingTop: 42,
  },
  pagerSectionTitle: {
    color: '#10161F',
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 24,
  },
  sectionTitleAccent: {
    color: '#4C88A4',
  },
  sectionLoader: {
    marginTop: 42,
  },
  eventList: {
    gap: 14,
    marginTop: 20,
  },
  eventCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 24,
  },
  eventCardHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  eventTitle: {
    color: '#10161F',
    flex: 1,
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 24,
  },
  eventImage: {
    backgroundColor: '#DDEBF2',
    borderRadius: 8,
    height: 58,
    width: 78,
  },
  eventInfoRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 9,
    marginTop: 14,
  },
  eventInfoText: {
    color: '#10161F',
    flex: 1,
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 20,
  },
  eventDescription: {
    color: '#6D7477',
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 21,
    marginTop: 14,
  },
  emptySection: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    marginTop: 30,
    paddingHorizontal: 18,
    paddingVertical: 32,
  },
  emptySectionText: {
    color: '#6D7477',
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 21,
    textAlign: 'center',
  },
  missionSection: {
    backgroundColor: '#F6F9FB',
    minHeight: 500,
    paddingBottom: 50,
    paddingTop: 42,
  },
  missionCardList: {
    gap: 0,
    paddingTop: 10,
  },
  missionCardScroller: {
    marginHorizontal: -16,
  },
  missionCard: {
    borderRadius: 32,
    height: 348,
    overflow: 'hidden',
    paddingHorizontal: 20,
    paddingTop: 45,
    width: 251,
  },
  missionCardSea: {
    backgroundColor: '#ABD4E3',
  },
  missionCardMountain: {
    backgroundColor: '#B8D7C2',
  },
  missionCardCity: {
    backgroundColor: '#304957',
  },
  missionBadge: {
    alignSelf: 'center',
    borderColor: '#5C7C8A',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 3,
  },
  missionBadgeText: {
    color: '#456778',
    fontSize: 11,
    lineHeight: 16,
  },
  missionCardTitle: {
    color: '#243A4A',
    fontSize: 20,
    fontWeight: '700',
    lineHeight: 29,
    marginTop: 14,
    textAlign: 'center',
  },
  missionCardImage: {
    alignSelf: 'center',
    height: 206,
    marginTop: 7,
    width: 220,
  },
  missionCardImagePlaceholder: {
    height: 206,
    marginTop: 7,
  },
  missionCardDescription: {
    color: '#456778',
    fontSize: 12,
    lineHeight: 19,
    marginTop: 2,
    textAlign: 'center',
  },
  missionListIconArea: {
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  missionListIcon: {
    height: '88%',
    width: '88%',
  },
  mapMissionCard: {
    flexShrink: 0,
  },
});
