// 검색 화면에서 사용하는 스타일 모음입니다.
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    backgroundColor: '#FFFFFF',
    flex: 1,
    paddingHorizontal: 16,
  },
  title: {
    color: '#10161F',
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 25,
  },
  searchField: {
    alignItems: 'center',
    backgroundColor: '#F6F6F6',
    borderRadius: 28,
    flexDirection: 'row',
    height: 52,
    marginTop: 40,
    paddingHorizontal: 28,
  },
  input: {
    color: '#10161F',
    flex: 1,
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 22,
    marginLeft: 10,
    paddingVertical: 0,
  },
  clearButton: {
    alignItems: 'center',
    backgroundColor: '#92999B',
    borderRadius: 999,
    height: 22,
    justifyContent: 'center',
    width: 22,
  },
  typeSelector: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 14,
  },
  typeChip: {
    borderColor: '#D9E0E3',
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  typeChipSelected: {
    backgroundColor: '#E5F2F8',
    borderColor: '#74B1C9',
  },
  typeChipText: {
    color: '#8A9194',
    fontSize: 11,
    fontWeight: '500',
    lineHeight: 16,
  },
  typeChipTextSelected: {
    color: '#4C88A4',
    fontWeight: '600',
  },
  content: {
    paddingBottom: 40,
  },
  recentHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 39,
  },
  sectionTitle: {
    color: '#10161F',
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 24,
  },
  deleteAll: {
    color: '#8A9194',
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 20,
  },
  emptyRecent: {
    color: '#8A9194',
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 18,
    marginTop: 41,
    textAlign: 'center',
  },
  chipList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 14,
  },
  recentChip: {
    alignItems: 'center',
    borderColor: '#D9E0E3',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 9,
    minHeight: 36,
    paddingHorizontal: 12,
  },
  recentChipPressable: {
    alignItems: 'center',
    flexDirection: 'row',
    minHeight: 34,
  },
  recentChipText: {
    color: '#10161F',
    fontSize: 12,
    fontWeight: '500',
  },
  recommendedTitle: {
    marginTop: 70,
  },
  recommendedChip: {
    alignItems: 'center',
    backgroundColor: '#EAF4F9',
    borderRadius: 18,
    minHeight: 36,
    paddingHorizontal: 14,
  },
  recommendedChipText: {
    color: '#659AB3',
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 36,
  },
  resultsContent: {
    gap: 18,
    paddingBottom: 30,
    paddingTop: 44,
  },
  resultCard: {
    backgroundColor: '#F7FAFC',
    borderRadius: 17,
    minHeight: 237,
    paddingHorizontal: 26,
    paddingVertical: 25,
  },
  resultHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  resultHeading: {
    flex: 1,
    paddingTop: 1,
  },
  resultTitle: {
    color: '#10161F',
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 23,
  },
  resultLocation: {
    color: '#10161F',
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 22,
    marginTop: 1,
  },
  resultImage: {
    backgroundColor: '#DDEBF2',
    borderRadius: 8,
    height: 77,
    width: 113,
  },
  resultImagePlaceholder: {
    backgroundColor: '#DDEBF2',
    borderRadius: 8,
    height: 77,
    width: 113,
  },
  resultDescription: {
    color: '#8A9194',
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 18,
    marginTop: 23,
  },
  resultTags: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    marginTop: 14,
  },
  resultTag: {
    alignItems: 'center',
    backgroundColor: '#C9E4EE',
    borderRadius: 18,
    flexDirection: 'row',
    gap: 6,
    minHeight: 35,
    paddingHorizontal: 12,
  },
  resultTagText: {
    color: '#2F7F9A',
    fontSize: 12,
    fontWeight: '500',
  },
  searchMessage: {
    color: '#8A9194',
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 18,
    paddingHorizontal: 12,
    paddingTop: 48,
    textAlign: 'center',
  },
  loadingState: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'flex-start',
    paddingTop: 48,
  },
  errorState: {
    flex: 1,
  },
  loadingMore: {
    paddingVertical: 12,
  },
  detailHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    height: 44,
    justifyContent: 'space-between',
  },
  detailBackButton: {
    alignItems: 'center',
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  detailHeaderTitle: {
    color: '#10161F',
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 24,
  },
  detailHeaderSpacer: {
    height: 40,
    width: 40,
  },
  detailContent: {
    paddingBottom: 40,
    paddingTop: 16,
  },
  detailImage: {
    backgroundColor: '#DDEBF2',
    borderRadius: 16,
    height: 210,
    width: '100%',
  },
  detailImagePlaceholder: {
    backgroundColor: '#DDEBF2',
    borderRadius: 16,
    height: 210,
    width: '100%',
  },
  detailTitle: {
    color: '#10161F',
    fontSize: 22,
    fontWeight: '700',
    lineHeight: 31,
    marginTop: 22,
  },
  detailAddress: {
    color: '#596268',
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 22,
    marginTop: 3,
  },
  detailPhone: {
    color: '#659AB3',
    fontSize: 13,
    fontWeight: '500',
    lineHeight: 20,
    marginTop: 5,
  },
  detailSectionTitle: {
    color: '#10161F',
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 24,
    marginTop: 32,
  },
  detailOverview: {
    color: '#596268',
    fontSize: 13,
    fontWeight: '500',
    lineHeight: 21,
    marginTop: 12,
  },
  petInfoCard: {
    backgroundColor: '#F7FAFC',
    borderRadius: 14,
    marginTop: 12,
    paddingHorizontal: 16,
    paddingVertical: 6,
  },
  petInfoRow: {
    borderBottomColor: '#E8EEF1',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 12,
    paddingVertical: 11,
  },
  petInfoLabel: {
    color: '#8A9194',
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 19,
    width: 88,
  },
  petInfoValue: {
    color: '#303941',
    flex: 1,
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 19,
  },
  missionRecommendationList: {
    gap: 14,
    marginTop: 12,
  },
  missionRecommendationCard: {
    backgroundColor: '#F7FAFC',
    borderRadius: 16,
    paddingHorizontal: 18,
    paddingVertical: 18,
  },
  missionRecommendationHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  missionRecommendationHeading: {
    flex: 1,
    paddingRight: 12,
  },
  missionRecommendationTitle: {
    color: '#10161F',
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 23,
  },
  missionRecommendationPlace: {
    color: '#596268',
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 19,
    marginTop: 3,
  },
  missionRecommendationDistance: {
    color: '#659AB3',
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 19,
    marginTop: 2,
  },
  missionRecommendationImage: {
    backgroundColor: '#DDEBF2',
    borderRadius: 8,
    height: 76,
    width: 110,
  },
  missionRecommendationImagePlaceholder: {
    backgroundColor: '#DDEBF2',
    borderRadius: 8,
    height: 76,
    width: 110,
  },
  missionRecommendationDescription: {
    color: '#596268',
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 19,
    marginTop: 16,
  },
  matchReasons: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 7,
    marginTop: 13,
  },
  matchReason: {
    backgroundColor: '#E5F2F8',
    borderRadius: 15,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  matchReasonText: {
    color: '#659AB3',
    fontSize: 11,
    fontWeight: '500',
    lineHeight: 16,
  },
  detailLoadingState: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
  },
  detailMessageState: {
    flex: 1,
  },
});
